icon: mdi:security
title: Security
id: security
cards:
  - type: alarm-panel
    entity: alarm_control_panel.blink_xt_hub
    states:
      - arm_away

  - type: vertical-stack
    cards:
      - type: horizontal-stack
        cards:
          - type: sensor
            entity: sensor.blink_camera1_temperature_2
          - type: sensor
            entity: sensor.blink_cameraks_temperature

      - type: horizontal-stack
        cards:
          - type: sensor
            entity: sensor.blink_camera1_battery_2
          - type: sensor
            entity: sensor.blink_cameraks_battery

  - type: picture-entity
    entity: camera.blink_gif

  - type: picture-entity
    entity: camera.blink_camera1_2

  - type: picture-entity
    entity: camera.blink_cameraks
