language: python
python: "3.6"

env:
    - HASS='homeassistant'
    - HASS='--pre homeassistant'

before_install:
    - mv travis_secrets.yaml secrets.yaml; touch /tmp/test.txt
    - sed -i -e 's/\/images/\/tmp/g' configuration.yaml
    - python3 -m venv .
    - source /bin/activate
    - pip3 install colorama
    - pip3 install colorlog

script:
    - pip3 install --upgrade $HASS
    - hass -c . --script check_config --info all
    - /bin/bash ./bin/smash.sh --travis && hass -c . --script check_config --info all
