language: python
python: "3.6"

env:
    - HASS='homeassistant'
    - HASS='--pre homeassistant'

before_install:
    - mv travis_secrets.yaml secrets.yaml; touch /tmp/test.txt
    - sed -i -e 's/\/images/\/tmp/g' configuration.yaml
    - sudo apt-get update && sudo apt-get install -y libudev-dev 

install:
    - pip3 install $HASS && pip3 install colorama && pip3 install colorlog
   
script:
    - hass -c . --script check_config --info all
    - /bin/bash ./bin/smash.sh --travis && hass -c . --script check_config --info all
