language: python
python: "3.6"

env:
    - HASS='homeassistant'
    - HASS='--pre homeassistant'

before_install:
    - mv travis_secrets.yaml secrets.yaml; touch /tmp/test.txt
    - sed -i -e 's/\/images/\/tmp/g' configuration.yaml
    - sed -i -e 's/hue\:\s\!include\sincludes\/hue\.yaml//g' configuration.yaml

script:
    - pip3 install $HASS && pip3 install colorama && pip3 install colorlog
    - hass -c . --script check_config
    - /bin/bash ./bin/smash.sh --travis && hass -c . --script check_config
