language: python
python:
    - "3.4.2" 
before_install:
    - mv travis_secrets.yaml secrets.yaml
install:
    - pip3 install homeassistant && pip3 install colorama
script:
    - touch /tmp/test.txt
    - hass -c . --script check_config
    - /bin/bash ./bin/smash.sh --travis && hass -c . --script check_config
    
