language: python

env:
    - HASS='latest'
    - HASS='beta'

services:
  - docker

before_install:
  - mv travis_secrets.yaml secrets.yaml; touch /tmp/test.txt
  - sed -i -e 's/\/images/\/tmp/g' configuration.yaml
  - docker pull homeassistant/home-assistant:$HASS
  - docker run --init -d --name="home-assistant" -e "TZ=America/New_York" -v /tmp:/tmp -v $TRAVIS_BUILD_DIR:/config homeassistant/home-assistant:$HASS
  - docker ps -a
  - docker exec home-assistant pip install -r /config/requirements.txt
 
script:
    - docker exec home-assistant python -m homeassistant --script check_config --config /config -f
