language: python
python:
    - "3.4.2" 
before_install:
    - mv travis_secrets.yaml secrets.yaml
install:
    - pip3 install homeassistant
script:
    - hass -c . --script check_config
    - python gen_automations.python
    - hass -c . --script check_config