# Time/Sun Based (Timers)
- !include automation/sunset.yaml
- !include automation/outside_off.yaml
- !include automation/inside_off.yaml
- !include automation/wake.yaml

# Presence Based
- !include automation/away.yaml
- !include automation/home.yaml
- !include automation/rainy.yaml

# Thermostat
- !include automation/thermostat_home.yaml
- !include automation/thermostat_away.yaml