#---------------- SMASH.PY ------------------
# Generated: 2018-Mar-31 20:40:50 
#--------------------------------------------

#--- automation/thermostat_disable.yaml ---
- id: thermostat_disable
  alias: Thermostat Disable
  trigger:
    - platform: state
      entity_id: input_boolean.thermostat_enable
      to: 'off'
  action:
    - service: climate.set_operation_mode
      entity_id: climate.living_room
      data:
        operation_mode: 'off'

#--- automation/notify_washer_status.yaml ---
- id: notify_on_washer_status
  alias: Notify on Washer Status
  trigger:
    - platform: state
      entity_id: sensor.washer
      from: 'Not Running'
      to: 'Running'
    - platform: state
      entity_id: sensor.washer
      from: 'Running'
      to: 'Not Running'
  action:
    - service: script.notify_all_engine
      data:
        call_washer_status: 1
    - service: script.speech_engine
      data:
        call_washer_status: 1

#--- automation/lights_rainy.yaml ---
#Turn on couch lights if it's raining, someone
# is home, and it's after 11am.
- id: lights_rainy
  alias: Lights Rainy
  trigger:
    - platform: state
      entity_id: sensor.pws_weather
      to: 'Rain'
  condition:
    condition: and
    conditions:
      - condition: time
        after: '07:00'
        before: '18:00'
      - condition: state
        entity_id: sensor.occupancy
        state: 'home'
  action:
    service: light.turn_on
    entity_id: group.couch

#--- automation/notify_on_fire_co2.yaml ---
- id: notify_on_fire_co2
  alias: Notify on Fire/CO2
  trigger:
    - platform: state
      entity_id: sensor.smoke_alarm_kitchen
      to: "Fire"
    - platform: state
      entity_id: sensor.smoke_alarm_kitchen
      to: "CO2"
    - platform: state
      entity_id: sensor.smoke_alarm_living_room
      to: "Fire"
    - platform: state
      entity_id: sensor.smoke_alarm_living_room
      to: "CO2"
    - platform: state
      entity_id: sensor.smoke_alarm_nursery
      to: "Fire"
    - platform: state
      entity_id: sensor.smoke_alarm_nursery
      to: "CO2"
  action:
    - service: script.notify_all_engine
      data:
        call_fire_co2: 1
    - service: script.speech_engine
      data:
        call_fire_co2: 1

#--- automation/notify_on_way_home.yaml ---
- id: notify_on_way_home
  alias: Notify on Way Home
  trigger:
    - platform: state
      entity_id: input_boolean.on_the_way_home
      to: 'on'
  action:
    - service: script.notify_all_engine
      data:
        call_on_way_home: 1

#--- automation/lights_not_home.yaml ---
# Turn on lights if we're not home and it's dark out
- id: lights_not_home
  alias: Lights Not Home
  trigger:
    - platform: sun
      event: sunset
      offset: '-00:15:00'
    - platform: state
      entity_id: sensor.occupancy
      to: 'not_home'
  condition:
    condition: and
    conditions:
      - condition: time
        after: '16:00:00'
        before: '22:00:00'
      - condition: state
        entity_id: sensor.occupancy
        state: 'not_home'
  action:
    service: light.turn_on
    entity_id: group.couch
  

#--- automation/lights_outside_off.yaml ---
# Turn on outside lights off at 12:40 am
  
- id: lights_outdoor_off
  alias: Lights Outdoor Off
  trigger:
    - platform: time
      at: '00:40:07'
  action:
    - service: light.turn_off
      entity_id: group.exterior
    - service: switch.turn_off
      entity_id: group.outdoor_switches
    - service: switch.turn_off    
      entity_id: switch.driveway_switch

#--- automation/tts_garbage_night.yaml ---
- id: tts_garbage_night
  alias: TTS Garbage Night
  trigger:
    platform: time
    at: '20:00:00'
  action:
    service: script.speech_engine
    data:
      call_garbage_night: 1

#--- automation/lights_wake.yaml ---
# Turn lights on in the morning 
- id: lights_wakeup
  alias: Lights Wakeup
  trigger:
    - platform: time
      at: '6:30:33'
  action:
    - service: light.turn_on
      entity_id:
        - light.couch_left
        - light.kitchen_table

#--- automation/lights_inside_off.yaml ---
# Turn inside lights off around midnight (before exterior)
  
- id: lights_inside_off
  alias: Lights Inside Off
  trigger:
    - platform: time
      at: '00:12:09'
  action:
    - service: light.turn_off
      entity_id: group.interior

#--- automation/notify_on_failed_login.yaml ---
- id: notify_on_failed_login
  alias: Notify on Failed Login
  trigger:
    - platform: state
      entity_id: sensor.fail2ban_nginxhttpauth
    - platform: state
      entity_id: sensor.fail2ban_hassiptables
    - platform: state
      entity_id: sensor.fail2ban_organizrauth
  condition:
    condition: or
    conditions:
      - condition: template
        value_template: '{{ states.sensor.fail2ban_hassiptables.state != "None" }}'
      - condition: template
        value_template: '{{ states.sensor.fail2ban_organizrauth.state != "None" }}'
      - condition: template
        value_template: '{{ states.sensor.fail2ban_nginxhttpauth.state != "None" }}'
  action:
    - service: script.notify_kevin_engine
      data:
        call_failed_login: 1

#--- automation/lights_away.yaml ---
# Turn lights off when everyone leaves for work
# group.all_devices is 'not_home' if ALL devices are not home
# Only do this between 7:30am to 10:00am
  
- id: lights_away
  alias: Lights Away
  trigger:
    - platform: state
      entity_id: sensor.occupancy
      to: 'not_home'
    - platform: time
      at: '9:00:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.occupancy
        state: 'not_home'
      - condition: time
        after: '7:30:00'
        before: '10:00:00'
      - condition: state
        entity_id: input_boolean.guest_mode
        state: 'off'
  action:
    service: light.turn_off
    entity_id: group.all_lights
      

#--- automation/media_movies.yaml ---
- id: movie_colors
  alias: Movie Colors
  trigger:
    - platform: state
      entity_id: sensor.media_state
    - platform: state
      entity_id: media_player.shield_android_tv
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sensor.occupancy
        state: 'home'
      - condition: state
        entity_id: input_boolean.movie_colors
        state: 'on'
  action:
    - service: python_script.media_engine
  

#--- automation/notify_on_restart.yaml ---
- id: notify_on_restart
  alias: Notify on Restart
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: script.notify_kevin_engine
      data:
        call_on_restart: 1
    - service_template: >
        {% if now().month == 12 %}
          input_boolean.turn_on
        {% else %}
          input_boolean.turn_off
        {% endif %}
      entity_id: input_boolean.christmas_lights

#--- automation/thermostat_change.yaml ---
- id: thermostat_change_on_weather
  alias: Thermostat Change on Weather
  trigger:
    - platform: time
      at: '22:30:00'
    - platform: time
      at: '06:00:00'
    - platform: state
      entity_id: input_boolean.thermostat_enable
      to: 'on'
    - platform: state
      entity_id: input_boolean.guest_mode
      to: 'on'
    - platform: state
      entity_id: input_boolean.guest_mode
      to: 'off'
    - platform: state
      entity_id: input_boolean.on_the_way_home
      to: 'on'
    - platform: state
      entity_id: input_boolean.warmer_night_mode
    - platform: state
      entity_id: sensor.occupancy
      to: 'home'
    - platform: state
      entity_id: sensor.occupancy
      to: 'not_home'  
    - platform: numeric_state
      entity_id: sensor.pws_feelslike_f
      above: 77
    - platform: numeric_state
      entity_id: sensor.pws_feelslike_f
      below: 55
    - platform: numeric_state
      entity_id: sensor.pws_feelslike_f
      above: 58
      below: 74
    - platform: numeric_state
      entity_id: sensor.living_room_humidity
      above: 58
    - platform: numeric_state
      entity_id: sensor.living_room_humidity
      below: 55
    - platform: template
      value_template: '{{ (states.climate.living_room.attributes.current_temperature | float - states.sensor.pws_feelslike_f.state | float) > 2.0 }}'
    - platform: template
      value_template: '{{ (states.sensor.bedroom_temperature.state | int > 79) and (now().strftime("%H") | int > 21) }}'
    - platform: template
      value_template: '{{ (states.sensor.bedroom_temperature.state | int < 78) and ((now().strftime("%H") | int > 21) or (now().strftime("%H") | int < 5)) }}'
    - platform: homeassistant
      event: start
  action:
    - service: python_script.thermostat_engine

#--- automation/zwave_fix_dead_node.yaml ---
- id: fix_dead_zwave_node
  alias: Fix Dead ZWave Node
  trigger:
      - platform: template
        value_template: '{{states.zwave.driveway.attributes.is_failed}}'
      - platform: time
        at: '00:10:00'
  action:
      - service: script.zwave_fix_dead_node

#--- automation/thermostat_on_fridays.yaml ---
- id: 'heat_on_fridays'
  alias: 'Heat on Fridays'
  trigger:
    - platform: time
      at: '8:00:00'
  condition:
    - condition: time
      weekday:
      - fri
  action:
    - service: input_boolean.turn_on
      entity_id: input_boolean.guest_mode

#--- automation/lights_home.yaml ---
# Turn lights on when someone comes home from work
# group.all_devices is 'home' if ANY device is home
# Do this between 5pm and 7pm
  
- id: lights_home
  alias: Lights Home
  trigger:
    - platform: state
      entity_id: sensor.occupancy_no_guest
      to: 'home'
  condition:
    condition: and
    conditions:
      - condition: time
        after: '16:00:00'
        before: '19:00:00'
        weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
  action:
    - service: light.turn_on
      entity_id: group.couch
    - service: light.turn_on
      entity_id: light.kitchen_table
    - service: input_boolean.turn_off
      entity_id: input_boolean.guest_mode

#--- automation/lights_sunset.yaml ---
# Turn on outside lights 15 minutes after sunset
  
- id: lights_sunset
  alias: Lights Sunset
  trigger:
    - platform: sun
      event: sunset
      offset: '+00:15:00'
  action:
    - service: light.turn_on
      entity_id: light.porch_2
      data:
        brightness: 278
        color_temp: 330
    - service: switch.turn_on
      entity_id: switch.driveway_switch
    - service: script.speech_engine
      data:
        call_dark_outside: 1

#--- automation/lights_holiday_lights.yaml ---
# Turn on holiday lights at sunset
- id: lights_holiday_lights
  alias: Lights Holiday Lights
  trigger:
    - platform: sun
      event: sunset
      offset: '+00:16:00'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: 'input_boolean.christmas_lights'
        state: 'on'
  action:
    - service: switch.turn_on
      entity_id: group.outdoor_switches
    - service: light.turn_on
      entity_id: light.porch_2
      data:
        brightness: 174
        xy_color: [0.1903,0.6795]
