# Time/Sun Based (Timers)
- !include automation/sunset.yaml
- !include automation/outside_off.yaml
- !include automation/inside_off.yaml
- !include automation/wake.yaml

# Presence Based
- !include automation/away.yaml
- !include automation/home.yaml
- !include automation/rainy.yaml

# Thermostat
#- !include automation/hvac_set_mode.yaml
- !include automation/hvac_mode_list.yaml
- !include automation/hvac_away_mode.yaml
#- !include automation/hvac_resume_schedule.yaml
- !include automation/hvac_weather_turn_on.yaml
- !include automation/hvac_weather_turn_off.yaml
- !include automation/hvac_disable_weather.yaml
- !include automation/hvac_update_weather_track.yaml