#---------------- SMASH.PY ------------------
# Generated: 2020-Jul-25 20:08:08 
#--------------------------------------------

#--- automation/notify_on_failed_login.yaml ---
- id: notify_on_failed_login
  alias: Notify on Failed Login
  trigger:
    - platform: state
      entity_id: sensor.fail2ban_nginx_http_auth
    - platform: state
      entity_id: sensor.fail2ban_hass_iptables
    - platform: state
      entity_id: sensor.fail2ban_organizr_auth
  condition:
    condition: or
    conditions:
      - condition: template
        value_template: '{{ states.sensor.fail2ban_hass_iptables.state != "None" }}'
      - condition: template
        value_template: '{{ states.sensor.fail2ban_organizr_auth.state != "None" }}'
      - condition: template
        value_template: '{{ states.sensor.fail2ban_nginx_http_auth.state != "None" }}'
  action:
    - service: script.notify_kevin_engine
      data:
        call_failed_login: 1

#--- automation/lights_inside_off.yaml ---
# Turn inside lights off around midnight (before exterior)
  
- id: lights_inside_off
  alias: Lights Inside Off
  trigger:
    - platform: time
      at: '00:12:09'
  action:
    - service: light.turn_off
      entity_id: light.interior_lights

#--- automation/lights_outside_off.yaml ---
# Turn on outside lights off at 12:40 am
  
- id: lights_outdoor_off
  alias: Lights Outdoor Off
  trigger:
    - platform: time
      at: '00:40:07'
  action:
    - service: light.turn_off
      entity_id: light.porch
    - service: switch.turn_off
      entity_id: switch.driveway

#--- automation/notify_on_fire_co.yaml ---
- id: notify_on_fire_co
  alias: Notify on Fire/CO
  trigger:
    - platform: state
      entity_id: sensor.smoke_alarm_foyer
      to: "Fire"
    - platform: state
      entity_id: sensor.smoke_alarm_foyer
      to: "CO"
    - platform: state
      entity_id: sensor.smoke_alarm_family_room
      to: "Fire"
    - platform: state
      entity_id: sensor.smoke_alarm_family_room
      to: "CO"
    - platform: state
      entity_id: sensor.smoke_alarm_office
      to: "Fire"
    - platform: state
      entity_id: sensor.smoke_alarm_office
      to: "CO"
    - platform: state
      entity_id: sensor.smoke_alarm_basement
      to: "Fire"
    - platform: state
      entity_id: sensor.smoke_alarm_basement
      to: "CO"
  action:
    - service: notify.notify
      data_template:
        message: >
            ALERT! {{ now().strftime("%h %d, %Y at %H:%M:S") }} {{trigger.to_state.state}} detected by {{trigger.to_state.attributes.friendly_name}}

#--- automation/notify_on_restart.yaml ---
- id: notify_on_restart
  alias: Notify on Restart
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: script.notify_kevin_engine
      data:
        call_on_restart: 1

#--- automation/sunset.yaml ---
# Turn on outside lights 15 minutes after sunset
  
- id: lights_sunset
  alias: Lights Sunset
  trigger:
    - platform: sun
      event: sunset
      offset: '+00:15:00'
  action:
    - service: light.turn_on
      entity_id: light.porch
    - service: switch.turn_on
      entity_id: switch.driveway

#--- automation/notify_leak_detected.yaml ---
- id: notify_on_leak_detected
  alias: Notify on Leak Detected
  trigger:
    - platform: state
      entity_id: binary_sensor.leak_sump
      from: 'off'
      to: 'on'
  action:
    - service: notify.notify
      data_template:
        message: >
          ALERT! {{ now().strftime("%h %d, %Y at %H:%M:%S") }} Leak Detected with {{trigger.to_state.attributes.friendly_name}}   

#--- automation/night.yaml ---
- id: night_routine
  alias: Night Routine
  trigger:
    - platform: time
      at: '21:30:30'
  action:
    - service: light.turn_off
      entity_id:
        - light.kitchen_island
        - light.kitchen_table

#--- automation/wakeup.yaml ---
- id: wakeup_routine
  alias: Wakeup Routine
  trigger:
    - platform: time
      at: '06:30:30'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: 'sun.sun'
        state: 'below_horizon'
  action:
    - service: light.turn_on
      entity_id:
        - light.family_room_couch_left
        - light.family_room_couch_right

#--- automation/sunrise.yaml ---
# Turn off inside lights 15 minutes after sunrise
  
- id: lights_sunrise
  alias: Lights Sunrise
  trigger:
    - platform: sun
      event: sunrise
      offset: '+00:15:00'
  action:
    - service: light.turn_off
      entity_id:
        - light.family_room_couch_left
        - light.family_room_couch_right

#--- automation/thermostat_ac_off.yaml ---
- id: 'thermostat_ac_disable'
  alias: 'Thermostat AC Disable'
  trigger:
    - platform: numeric_state
      entity_id: sensor.weather_temperature
      below: 74 
  condition:
    - condition: template
      value_template: >
          {% set month=now().month | int %}
          {% if month >= 5 and month <= 9 %}
            true
          {% endif %}
  action:
    - service: climate.set_hvac_mode
      data:
        entity_id: climate.thermostat_1_nativezone
        hvac_mode: 'off'

#--- automation/thermostat_heat_off.yaml ---
- id: 'thermostat_heat_disable'
  alias: 'Thermostat Heat Disable'
  trigger:
    - platform: numeric_state
      entity_id: sensor.weather_temperature
      above: 67
  condition:
    - condition: template
      value_template: >
          {% set month=now().month | int %}
          {% if month <= 4 and month >= 9 %}
            true
          {% endif %}
  action:
    - service: climate.set_hvac_mode
      data:
        entity_id: climate.thermostat_1_nativezone
        hvac_mode: 'off'

#--- automation/thermostat_ac_on.yaml ---
- id: 'thermostat_ac_enable'
  alias: 'Thermostat AC Enable'
  trigger:
    - platform: numeric_state
      entity_id: sensor.weather_temperature
      above: 77
  condition:
    - condition: template
      value_template: >
          {% set month=now().month | int %}
          {% if month >= 5 and month <= 9 %}
            true
          {% endif %}
  action:
    - service: climate.set_hvac_mode
      data:
        entity_id: climate.thermostat_1_nativezone
        hvac_mode: 'cool'
    - delay:
        seconds: 15
    - service: climate.set_temperature
      data_template:
        entity_id: climate.thermostat_1_nativezone
        hvac_mode: 'cool'
        temperature: > 
            {{ states.input_number.ac_setpoint.state }}

#--- automation/thermostat_heat_on.yaml ---
- id: 'thermostat_heat_enable'
  alias: 'Thermostat Heat Enable'
  trigger:
    - platform: numeric_state
      entity_id: sensor.weather_temperature
      below: 64
  condition:
    - condition: template
      value_template: >
          {% set month=now().month | int %}
          {% if month <= 4 and month >= 9 %}
            true
          {% endif %}
  action:
    - service: climate.set_hvac_mode
      data:
        entity_id: climate.thermostat_1_nativezone
        hvac_mode: 'heat'
    - delay:
        seconds: 15
    - service: climate.set_temperature
      data_template:
        entity_id: climate.thermostat_1_nativezone
        hvac_mode: 'heat'
        temperature: >
            {% set target = states.input_number.heat_setpoint.state | int %}
            {% set delta = states.input_number.heat_emergency_delta.state | int %}
            {% if (states.sensor.weather_temperature.state | int) < 30 %}
              {{ target - delta }}
            {% else %}
              {{ target }}
            {% endif %}

#--- automation/evening.yaml ---
- id: evening_routine
  alias: Evening Routine
  trigger:
    - platform: sun
      event: sunset
      offset: '-01:30:00'
  action:
    - service: light.turn_on
      entity_id:
        - light.family_room_couch_left
        - light.family_room_couch_right
        - light.kitchen_island
        - light.kitchen_table
        - light.living_room_couch

#--- automation/cloudy.yaml ---
# Turn on inside light if it's cloudy midday
- id: lights_cloudy
  alias: Lights Cloudy
  trigger:
    - platform: numeric_state
      entity_id: sensor.weather_cloudiness
      above: 60
    - platform: numeric_state
      entity_id: sensor.weather_precipitation
      above: 0.05
  condition:
    condition: and
    conditions:
      - condition: time
        after: '10:00:00'
        before: '20:00:00'
      - condition: state
        entity_id: sun.sun
        state: 'above_horizon'
  action:
    - service: light.turn_on
      entity_id:
        - light.family_room_couch_left
        - light.family_room_couch_right
        - light.living_room_couch 

#--- automation/sunny.yaml ---
# Turn off lights inside if it's sunny
- id: lights_sunny
  alias: Lights Sunny
  trigger:
    - platform: numeric_state
      entity_id: sensor.weather_cloudiness
      below: 20
  condition:
    condition: and
    conditions:
      - condition: time
        after: '12:00:00'
        before: '15:00:00'
      - condition: state
        entity_id: light.living_room_couch
        state: 'on'
  action:
    - service: light.turn_off
      entity_id:
        - light.family_room_couch_left
        - light.family_room_couch_right
        - light.living_room_couch
