homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 154
  temperature_unit: F
  time_zone: America/New_York
  customize: !include customize.yaml
  unit_system: imperial
  whitelist_external_dirs:
    - /images
  auth_providers:
    - type: homeassistant
    - type: legacy_api_password

http:
  api_password: !secret password
  use_x_forwarded_for: True
  trusted_proxies:
    - 172.17.0.0/22

# Includes
automation: !include automations.yaml
blink: !include includes/blink.yaml
camera: !include includes/cameras.yaml
#device_tracker: !include includes/device_trackers.yaml
emulated_hue: !include includes/emulated_hue.yaml
google_assistant: !include includes/google_assistant.yaml
#gpslogger:
group: !include_dir_merge_named groups
hue: !include includes/hue.yaml
history: !include includes/history.yaml
input_boolean: !include includes/input_boolean.yaml
input_number: !include includes/input_number.yaml
influxdb: !include includes/influxdb.yaml
logger: !include includes/logger.yaml
media_player: !include includes/media.yaml
notify: !include includes/notify.yaml
python_script:
recorder: !include includes/recorder.yaml
scene: !include_dir_list scenes
script: !include scripts.yaml
sensor: !include_dir_merge_list sensors
shell_command: !include includes/shell_command.yaml
tts: !include includes/tts.yaml
zwave: !include includes/zwave.yaml

# Enables
frontend:
config:
logbook:
sun:
updater:
  reporting: False

#==========================================
# Other components
#==========================================
#wake_on_lan:

ecobee:
  api_key: !secret ecobee_api

