homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 154
  temperature_unit: F
  time_zone: America/New_York
  customize: !include_dir_merge_named customize
  unit_system: imperial
  
http:
  api_password: !secret password
  ssl_certificate: !secret cert_location
  ssl_key: !secret key_location
  base_url: !secret ha_url
 
# Includes
automation: !include_dir_list automation
camera: !include includes/cameras.yaml
device_tracker: !include includes/device_trackers.yaml
group: !include_dir_merge_named groups
history: !include includes/history.yaml
input_boolean: !include includes/input_boolean.yaml
input_select: !include includes/input_select.yaml
media_player: !include includes/media.yaml
recorder: !include includes/recorder.yaml
scene: !include_dir_list scenes
script: !include_dir_merge_named scripts
sensor: !include_dir_list sensors
zwave: !include includes/zwave.yaml

# Enables
frontend:
discovery:
sun:
updater:
  reporting: False

logbook:

# No need to clog up log with useless stuff
logger:
  default: warning
  logs:
    homeassistant.components.sensor: warning
    homeassistant.components.media_player: critical
    homeassistant.components.camera: debug

#==========================================
# Other components (wink, hue, etc)
#==========================================
wink:
  email: !secret wink_email
  password: !secret wink_password

light:
  platform: hue
  host: 192.168.86.191
  allow_unreachable: true
  
emulated_hue:
  host_ip: 192.168.86.89
  type: google_home
  listen_port: 80
  expose_by_default: false
  exposed_domains:
    - light
    - group
    - input_boolean
    - scene

ecobee:
  api_key: !secret ecobee_api
  hold_temp: True

#blink:
#  username: !secret blink_username
#  password: !secret blink_password

notify:
  - name: notify
    platform: html5
    gcm_api_key: !secret gcm_api_key
    gcm_sender_id: !secret gcm_sender_id
 
tts:
  - platform: google
    cache: true
