homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 154
  temperature_unit: F
  time_zone: America/New_York
  customize: !include_dir_merge_named customize
  unit_system: imperial
  
http:
  api_password: !secret password
  ssl_certificate: !secret cert_location
  ssl_key: !secret key_location
  base_url: !secret ha_url
  
# Includes
automation: !include automation.yaml
camera: !include cameras.yaml
device_tracker: !include device_trackers.yaml
group: !include_dir_merge_named groups
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
media_player: !include media.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
#switch: !include switch.yaml

# Enables
frontend:
discovery:
sun:
updater:
  reporting: False

logbook:

# No need to clog up log with useless stuff
logger:
  default: warn
  logs:
    homeassistant.components.sensor: warning
    homeassistant.components.media_player: critical

# For history, want to keep database to manageable size
# so dump data after 30 days and only track useful
# information (ie. don't care about light/switch stuff)
recorder:
  purge_days: 30
history:
  exclude:
    domains:
      - light
      - switch
      - input_boolean
      - group
      - media_player
      
#==========================================
# Other components (wink, hue, etc)
#==========================================
wink:
  #access_token: !secret wink_api
  email: !secret wink_email
  password: !secret wink_password
  client_id: !secret wink_client_id
  client_secret: !secret wink_client_secret

light:
  platform: hue
  host: 192.168.86.191
  allow_unreachable: true
  
emulated_hue:
  host_ip: 192.168.86.89
  type: google_home
  listen_port: 80
  expose_by_default: false
  exposed_domains:
    - light
    - group
    - input_boolean
    - scene

ecobee:
  api_key: !secret ecobee_api
  hold_temp: True

zwave:
  usb_path: /dev/ttyACM0
  
notify:
  - name: notify
    platform: pushbullet
    api_key: !secret pushbullet_api
 
tts:
  - platform: google
    cache: true
    
