homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 154
  temperature_unit: F
  time_zone: America/New_York
  customize: !include customize.yaml
  unit_system: imperial
  
http:
  api_password: !secret password
  
# Includes
device_tracker: !include device_trackers.yaml
sensor: !include sensors.yaml
automation: !include automation.yaml
group: !include groups.yaml
media_player: !include media.yaml
camera: !include cameras.yaml
scene: !include scenes.yaml
input_slider: !include input_sliders.yaml
input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml
script: !include scripts.yaml

# Enables
logbook:
history:
#discovery:
sun:
frontend:
conversation:
updater:

# Other stuff
wink:
  access_token: !secret wink_api
  refresh_token: !secret wink_api_refresh

ecobee:
  api_key: !secret ecobee_api
  hold_temp: True
