homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 154
  temperature_unit: F
  time_zone: America/New_York
  customize: !include_dir_merge_named customize
  unit_system: imperial
  
http:
  api_password: !secret password
  ssl_certificate: !secret cert_location
  ssl_key: !secret key_location
  base_url: !secret ha_url
 
# Includes
automation: !include_dir_list automation
camera: !include includes/cameras.yaml
device_tracker: !include includes/device_trackers.yaml
emulated_hue: !include includes/emulated_hue.yaml
group: !include_dir_merge_named groups
history: !include includes/history.yaml
input_boolean: !include includes/input_boolean.yaml
input_select: !include includes/input_select.yaml
light: !include includes/light.yaml
logger: !include includes/logger.yaml
media_player: !include includes/media.yaml
notify: !include includes/notify.yaml
recorder: !include includes/recorder.yaml
scene: !include_dir_list scenes
script: !include_dir_merge_named scripts
sensor: !include_dir_list sensors
zwave: !include includes/zwave.yaml

# Enables
frontend:
# discovery:
logbook:
sun:
updater:
  reporting: False

#==========================================
# Other components
#==========================================
ecobee:
  api_key: !secret ecobee_api
  hold_temp: True
