homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 154
  temperature_unit: F
  time_zone: America/New_York
  customize: !include_dir_merge_named customize
  unit_system: imperial
  
http:
  api_password: !secret password
  
# Includes
automation: !include automation.yaml
camera: !include cameras.yaml
device_tracker: !include device_trackers.yaml
group: !include_dir_merge_named groups
input_boolean: !include input_boolean.yaml
input_select: !include input_select.yaml
media_player: !include media.yaml
scene: !include scenes.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
switch: !include switch.yaml

# Enables
frontend:
discovery:
sun:
updater:
  reporting: False

# Only include useful stuff in logs
# Basically, get rid of anything that updates
# in set intervals
logbook:
  exclude:
    domains: 
      - sensor
  include:
    entities:
      - sensor.occupancy
      - sensor.thermo_mode
      - sensor.thermo_hvac
      - sensor.thermo_fan
      - sensor.thermo_current_operation
      - sensor.thermo_outside_temp
    
  
# No need to clog up log with useless stuff
logger:
  default: warn
  logs:
    homeassistant.components.sensor: error
    homeassistant.components.media_player: critical

# For history, want to keep database to manageable size
# so dump data after 10 days and only track useful
# information (ie. don't care about light/switch stuff)
recorder:
  purge_days: 10
history:
  include:
    domains:
      - sensor
      - climate
      - device_trackers

#==========================================
# Other components (wink, hue, etc)
#==========================================
wink:
  #access_token: !secret wink_api
  email: !secret wink_email
  password: !secret wink_password
  client_id: !secret wink_client_id
  client_secret: !secret wink_client_secret

emulated_hue:
  exposed_domains:
    - light
    - group
    - input_boolean
    - scene
    - switch
    
light:
  platform: hue
  host: 192.168.86.191
 
ecobee:
  api_key: !secret ecobee_api
  hold_temp: True
  
panel_custom:
  - name: react
    sidebar_title: React
    sidebar_icon: mdi:vector-square
    url_path: todomvc
    config:
      title: Home
      
notify:
  - name: notify
    platform: pushbullet
    api_key: !secret pushbullet_api
  
