homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 154
  temperature_unit: F
  time_zone: America/New_York
  customize: !include_dir_merge_named customize
  unit_system: imperial
  
http:
  api_password: !secret password
  
# Includes
device_tracker: !include device_trackers.yaml
sensor: !include sensors.yaml
automation: !include automation.yaml
group: !include groups.yaml
media_player: !include media.yaml
camera: !include cameras.yaml
scene: !include scenes.yaml
#input_slider: !include input_sliders.yaml
input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml
script: !include scripts.yaml

# Enables
logbook:
#history:
discovery:
sun:
frontend:
updater:
  reporting: no
recorder:
  purge_days: 10
history:
  include:
    domains:
      - sensor
      - climate
      - device_trackers
  exclude:
    entities:
      - sensor.glances

# Other stuff
wink:
  access_token: !secret wink_api
  #refresh_token: !secret wink_api_refresh

emulated_hue:
  exposed_domains:
    - light
    - group
    - input_boolean
    - scene
 
light:
  platform: hue
  host: 192.168.86.191
 
ecobee:
  api_key: !secret ecobee_api
  hold_temp: True
 
panel_custom:
  - name: react
    sidebar_title: React
    sidebar_icon: mdi:vector-square
    url_path: todomvc
    config:
      title: Home
      
switch:
  - platform: flux
    lights:
      - light.corner
      - light.couch_left
      - light.couch_right
    start_colortemp: 3600
    stop_colortemp: 2500
    brightness: 255
    mode: mired
  
