homeassistant:
  name: Home
  latitude: !env_var LATITUDE
  longitude: !env_var LONGITUDE
  elevation: 154
  temperature_unit: F
  time_zone: America/New_York
  customize: !include customize.yaml
  unit_system: imperial

http:
  api_password: !env_var API_PASS
  
# Includes
device_tracker: !include device_trackers.yaml
sensor: !include sensors.yaml
automation: !include automation.yaml
group: !include groups.yaml
media_player: !include media.yaml
camera: !include cameras.yaml
scene: !include scenes.yaml
#input_slider: !include input_sliders.yaml
input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml
script: !include scripts.yaml

# Enables
logbook:
history:
discovery:
sun:
frontend:
conversation:
updater:

# Other stuff
wink:
  access_token: !env_var WINK_API
  refresh_token: !env_var WINK_REFRESH

ecobee:
  api_key: !env_var ECOBEE_API
  hold_temp: True
