homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 154
  temperature_unit: F
  time_zone: America/New_York
  customize: !include customize.yaml
  unit_system: imperial
  whitelist_external_dirs:
    - /images

http:
  use_x_forwarded_for: True
  trusted_proxies:
    - 172.17.0.0/22

# Includes
fakefakefake: !include doesnotexist.yaml
automation: !include automations.yaml
blink: !include includes/blink.yaml
camera: !include includes/cameras.yaml
climate: !include includes/climate.yaml
emulated_hue: !include includes/emulated_hue.yaml
fastdotcom: !include includes/fastdotcom.yaml
google_assistant: !include includes/google_assistant.yaml
group: !include_dir_merge_named groups
hue: !include includes/hue.yaml
history: !include includes/history.yaml
input_boolean: !include includes/input_boolean.yaml
input_number: !include includes/input_number.yaml
influxdb: !include includes/influxdb.yaml
logger: !include includes/logger.yaml
notify: !include includes/notify.yaml
pi_hole: !include includes/pihole.yaml
recorder: !include includes/recorder.yaml
scene: !include_dir_list scenes
script: !include scripts.yaml
sensor: !include_dir_merge_list sensors
shell_command: !include includes/shell_command.yaml
speedtestdotnet: !include includes/speedtest.yaml
system_health:
zwave: !include includes/zwave.yaml

# Enables
frontend:
config:
logbook:
sun:
updater:
  reporting: False
