# Sensors
- platform: openweathermap
  api_key: !env_var WEATHER_API
  monitored_conditions:
    - temperature
    - humidity
    - pressure
    - wind_speed
    
- platform: time_date
  display_options:
    - "date_time"
    
- platform: speedtest
  name: speedtest
  monitored_conditions:
    - ping
    - download
    - upload
    
