# Sensors
- !include sensors/thermostat.yaml
- !include sensors/speedtest.yaml
#- !include sensors/steam.yaml
- !include sensors/time.yaml
- !include sensors/darksky.yaml
- !include sensors/wunderground.yaml
#- !include sensors/weather.yaml
- !include sensors/kevin_commute_morning.yaml
- !include sensors/kevin_commute_evening.yaml
- !include sensors/allegra_commute_morning.yaml
- !include sensors/allegra_commute_evening.yaml
- !include sensors/glances.yaml
#- !include sensors/xbox.yaml
- !include sensors/statistics.yaml

# Stats sensors
- platform: statistics
  entity_id: sensor.living_room_temperature
  name: Living Room
  
- platform: statistics
  entity_id: sensor.bedroom_temperature
  name: Bedroom

- platform: statistics
  entity_id: sensor.speedtest_download
  name: Download
  
- platform: statistics
  entity_id: sensor.speedtest_upload
  name: Upload
  
- platform: statistics
  entity_id: sensor.glances_ram_use
  name: RAM
  
- platform: statistics
  entity_id: sensor.glances_cpu_load
  name: CPU