#===================================================
# Automations
#===================================================
automations_sun:
  name: Sun/Time Automations
  entities:
    - automation.lights_inside_off
    - automation.lights_sunset
    - automation.lights_wakeup
    - automation.lights_outdoor_off
    - automation.lights_holiday_lights
 
automations_presence:
  name: Presence Automations
  entities:
    - automation.lights_away
    - automation.lights_home
    - automation.lights_not_home
    - automation.lights_rainy
  
automations_hvac:
  name: Thermostat Automations
  entities:
    - automation.thermostat_change_on_weather
    - automation.thermostat_disable
    
automations_notify:
  name: Notification Automations
  entities:
    - automation.notify_on_washer_status
    - automation.notify_on_system_use
    - automation.notify_on_restart
    - automation.notify_on_fireco2
#    - automation.notify_on_ssl_expiry
    - automation.notify_on_way_home
    - automation.notify_on_failed_login
    - automation.tts_garbage_night
