- platform: template
  sensors: 
    leak_sump:
      value_template: >
        {% if is_state("sensor.aeon_labs_zw122_water_sensor_6_flood", "2") or is_state("sensor.aeon_labs_zw122_water_sensor_6_flood", "2") %}
          Wet
        {% else %}
          Dry
        {% endif %}
         
    smoke_alarm_foyer:
      value_template: >
        {% if is_state("sensor.smoke_detector_1_alarm_level", "0") %}
          Idle
        {% elif is_state("sensor.smoke_detector_1_alarm_type", "13") %}
          Idle
        {% elif is_state("sensor.smoke_detector_1_alarm_type", "12") %}
          Testing
        {% elif is_state("sensor.smoke_detector_1_alarm_type", "1") %}
          Fire
        {% elif is_state("sensor.smoke_detector_1_alarm_type", "2") %}
          CO
        {% else %}
          Unknown
        {% endif %}

    smoke_alarm_family_room:
      value_template: >
        {% if is_state("sensor.smoke_detector_2_alarm_level", "0") %}
          Idle
        {% elif is_state("sensor.smoke_detector_2_alarm_type", "13") %}
          Idle
        {% elif is_state("sensor.smoke_detector_2_alarm_type", "12") %}
          Testing
        {% elif is_state("sensor.smoke_detector_2_alarm_type", "1") %}
          Fire
        {% elif is_state("sensor.smoke_detector_2_alarm_type", "2") %}
          CO
        {% else %}
          Unknown
        {% endif %}
        
    smoke_alarm_office:
      value_template: >
        {% if is_state("sensor.smoke_detector_3_level", "0") %}
          Idle
        {% elif is_state("sensor.smoke_detector_3_alarm_type", "13") %}
          Idle
        {% elif is_state("sensor.smoke_detector_3_alarm_type", "12") %}
          Testing
        {% elif is_state("sensor.smoke_detector_3_alarm_type", "1") %}
          Fire
        {% elif is_state("sensor.smoke_detector_3_alarm_type", "2") %}
          CO
        {% else %}
          Unknown
        {% endif %}

    smoke_alarm_basement:
      value_template: >
        {% if is_state("sensor.smoke_detector_4_level", "0") %}
          Idle
        {% elif is_state("sensor.smoke_detector_4_alarm_type", "13") %}
          Idle
        {% elif is_state("sensor.smoke_detector_4_alarm_type", "12") %}
          Testing
        {% elif is_state("sensor.smoke_detector_4_alarm_type", "1") %}
          Fire
        {% elif is_state("sensor.smoke_detector_4_alarm_type", "2") %}
          CO
        {% else %}
          Unknown
        {% endif %}

    sump_rate_per_hour:
      value_template: >
        {% if (states.counter.timer.state | int) > 0 %}
          {{ float(((states.counter.sump_counter.state | int)*12 / (states.counter.timer.state | int)) | round(3)) }}
        {% else %}
          0.0
        {% endif %}
