- platform: template
  sensors: 
    radon:
      unit_of_measurement: 'pCi/L'
      value_template: "{{ (states.sensor.basement_radon.state | float * 1 / 37) | round(2) }}"
    radon_2:
      unit_of_measurement: 'pCi/L'
      value_template: "{{ (states.sensor.bedroom_radon.state | float * 1 / 37) | round(2) }}"


    smoke_alarm_foyer:
      value_template: >
        {% if is_state("sensor.smoke_detector_1_alarm_level", "0") %}
          Idle
        {% elif is_state("sensor.smoke_detector_1_alarm_type", "13") %}
          Idle
        {% elif is_state("sensor.smoke_detector_1_alarm_type", "12") %}
          Testing
        {% elif is_state("sensor.smoke_detector_1_alarm_type", "1") %}
          Fire
        {% elif is_state("sensor.smoke_detector_1_alarm_type", "2") %}
          CO
        {% else %}
          Unknown
        {% endif %}

    smoke_alarm_family_room:
      value_template: >
        {% if is_state("sensor.smoke_detector_2_alarm_level", "0") %}
          Idle
        {% elif is_state("sensor.smoke_detector_2_alarm_type", "13") %}
          Idle
        {% elif is_state("sensor.smoke_detector_2_alarm_type", "12") %}
          Testing
        {% elif is_state("sensor.smoke_detector_2_alarm_type", "1") %}
          Fire
        {% elif is_state("sensor.smoke_detector_2_alarm_type", "2") %}
          CO
        {% else %}
          Unknown
        {% endif %}
        
    smoke_alarm_office:
      value_template: >
        {% if is_state("sensor.smoke_detector_3_level", "0") %}
          Idle
        {% elif is_state("sensor.smoke_detector_3_alarm_type", "13") %}
          Idle
        {% elif is_state("sensor.smoke_detector_3_alarm_type", "12") %}
          Testing
        {% elif is_state("sensor.smoke_detector_3_alarm_type", "1") %}
          Fire
        {% elif is_state("sensor.smoke_detector_3_alarm_type", "2") %}
          CO
        {% else %}
          Unknown
        {% endif %}

    smoke_alarm_basement:
      value_template: >
        {% if is_state("sensor.smoke_detector_4_level", "0") %}
          Idle
        {% elif is_state("sensor.smoke_detector_4_alarm_type", "13") %}
          Idle
        {% elif is_state("sensor.smoke_detector_4_alarm_type", "12") %}
          Testing
        {% elif is_state("sensor.smoke_detector_4_alarm_type", "1") %}
          Fire
        {% elif is_state("sensor.smoke_detector_4_alarm_type", "2") %}
          CO
        {% else %}
          Unknown
        {% endif %}
