- platform: template
  sensors: 
    washer:
      value_template: >
        {% if states.sensor.power_mon_power %}
          {% if (states.sensor.power_mon_power.state | float) > 0.25 and (states.sensor.power_mon_power.state | float) < 8191.0 %}
            Running
          {% else %}
            Not Running
          {% endif %}
        {% else %}
        {% endif %}
        
    smoke_alarm_kitchen:
      value_template: >
        {% if is_state("sensor.smoke_kitchen_alarm_level", "0") %}
          Idle
        {% elif is_state("sensor.smoke_kitchen_alarm_type", "13") %}
          Idle
        {% elif is_state("sensor.smoke_kitchen_alarm_type", "12") %}
          Testing
        {% elif is_state("sensor.smoke_kitchen_alarm_type", "1") %}
          Fire
        {% elif is_state("sensor.smoke_kitchen_alarm_type", "2") %}
          CO2
        {% else %}
          Unknown
        {% endif %}

    smoke_alarm_living_room:
      value_template: >
        {% if is_state("sensor.smoke_living_room_alarm_level", "0") %}
          Idle
        {% elif is_state("sensor.smoke_living_room_alarm_type", "13") %}
          Idle
        {% elif is_state("sensor.smoke_living_room_alarm_type", "12") %}
          Testing
        {% elif is_state("sensor.smoke_living_room_alarm_type", "1") %}
          Fire
        {% elif is_state("sensor.smoke_living_room_alarm_type", "2") %}
          CO2
        {% else %}
          Unknown
        {% endif %}
        
    smoke_alarm_nursery:
      value_template: >
        {% if is_state("sensor.smoke_nursery_alarm_level", "0") %}
          Idle
        {% elif is_state("sensor.smoke_nursery_alarm_type", "13") %}
          Idle
        {% elif is_state("sensor.smoke_nursery_alarm_type", "12") %}
          Testing
        {% elif is_state("sensor.smoke_nursery_alarm_type", "1") %}
          Fire
        {% elif is_state("sensor.smoke_nursery_alarm_type", "2") %}
          CO2
        {% else %}
          Unknown
        {% endif %}
