- platform: command_line
  name: last_boot
  scan_interval: 480
  command: uptime | awk -F'( |,|:)+' '{print $6,$7,$8":"$9}'

- platform: uptime
  name: hass_uptime

- platform: version
  name: hass_version
