- platform: command_line
  name: last_boot
  scan_interval: 480
  command: uptime | awk -F'( |,|:)+' '{print $6,$7,$8":"$9}'

- platform: uptime
  name: hass_uptime

- platform: version
  name: hass_version

- platform: command_line
  name: pihole_version
  scan_interval: 20000
  command: ssh pi@192.168.86.89 "pihole -v" | grep "Pi-hole version" | awk -F'( )+' '{print $5" "$6" "$7}'
