- platform: darksky
  api_key: !secret darksky_api
  monitored_conditions:
    - visibility
    - ozone
    - temperature
    - precip_intensity
    - precip_probability
    - dew_point
    - temperature_high
    - temperature_low
    - precip_intensity_max
  units: us
