- platform: darksky
  api_key: !secret darksky_api
  monitored_conditions:
    - visibility
    - ozone
    - temperature
    - apparent_temperature
    - precip_intensity
    - precip_probability
    - dew_point
    - temperature_max
    - temperature_min
    - precip_intensity_max
  units: us
