- platform: darksky
  api_key: !secret darksky_api
  monitored_conditions:
    - temperature
    - daily_summary
    - apparent_temperature
    - dew_point
    - humidity
    - precip_intensity_max
    - precip_accumulation
    - pressure
    - visibility
    - wind_speed
    - wind_gust
    - wind_bearing
    - ozone
    - uv_index
  units: us
