- platform: glances
  name: glances
  host: !secret ha_ip_addr
  port: 61208
  resources:
    - 'disk_use_percent'
    - 'memory_use_percent'
    - 'swap_use_percent'
    - 'processor_load'
    - 'process_total'
