- platform: ups
  username: !secret ups_username
  password: !secret ups_password

- platform: template
  sensors:
    out_for_delivery:
      value_template: >
        {% set delivery_count = 0 %}
        {% if states.sensor.usps_packages.attributes.out_for_delivery %}
          {% set delivery_count = delivery_count + states.sensor.usps_packages.attributes.out_for_delivery | int %}
        {% endif %}
        {% if states.sensor.ups.attributes.out_for_delivery %}
          {% set delivery_count = delivery_count + states.sensor.ups.attributes.out_for_delivery | int %}
        {% endif %}
        {{ delivery_count }}