- platform: template
  sensors:
    media_type:
      value_template: >
        {% if states.media_player.shield_android_tv.attributes %}
          {{ states.media_player.shield_android_tv.attributes.media_library_name }}
        {% else %}
          None
        {% endif %}
    media_title:
      value_template: >
        {% if states.media_player.shield_android_tv.attributes %}
          {{ states.media_player.shield_android_tv.attributes.media_title }}
        {% else %}
          None
        {% endif %}
    media_state:
      value_template: >
        {% if states.media_player.shield_android_tv.state %}
          {{ states.media_player.shield_android_tv.state }}
        {% else %}
          None
        {% endif %}
