- platform: netdata
  name: netdata
  host: !secret server_url
  port: 19999
  resources:
    system.cpu:
        element: system
        name: cpu_system
    system.cpu:
        element: user
        name: cpu_user
    system.cpu:
        element: iowait
        name: cpu_iowait
    system.cpu:
        element: softirq
        name: cpu_softirq
    system.ram:
        element: free
        name: memory_free
    system.ram:
        element: used
        name: memory_used
    system.ram:
        element: cached
        name: memory_cached
    system.ipv4:
        element: received
        name: ipv4_in
    system.ipv4:
        element: sent
        name: ipv4_out

- platform: template
  sensors:
    netdata_cpu_total:
      unit_of_measurement: '%'
      value_template: >
        {{ (states.sensor.netdata_cpu_iowait.state | float + states.sensor.netdata_cpu_user.state | float + states.sensor.netdata_cpu_system.state | float + states.sensor.netdata_cpu_softirq.state | float + states.sensor.netdata_cpu_guest.state | float) | round(2) }}
    
