- platform: netdata
  name: netdata
  host: !secret server_url
  port: 19999
  resources:
    - memory_free
    - memory_used
    - memory_cached
    - ipv4_in
    - ipv4_out
    - cpu_iowait
    - cpu_user
    - cpu_system
    - cpu_softirq
    - cpu_guest

- platform: template
  sensors:
    netdata_cpu_total:
      unit_of_measurement: '%'
      value_template: >
        {{ (states.sensor.netdata_cpu_iowait.state | float + states.sensor.netdata_cpu_user.state | float + states.sensor.netdata_cpu_system.state | float + states.sensor.netdata_cpu_softirq.state | float + states.sensor.netdata_cpu_guest.state | float) | round(2) }}
    