- platform: template
  sensors:
    occupancy:
      value_template: >
        {% if states.device_tracker.kevin.state  %}
        {% if states.device_tracker.kevin.state == 'home' or states.device_tracker.allegra.state == 'home' or states.device_tracker.kevin_ping.state == 'home' or states.device_tracker.allegra_ping.state == 'home' %}
            home
          {% else %}
            not_home
          {% endif %}
        {% else %}
        {% endif %}


