- platform: openweathermap
  name: Weather
  api_key: !secret openweather_apikey
  monitored_conditions:
    - weather
    - temperature
    - wind_speed
    - wind_bearing
    - humidity
    - pressure
    - clouds
    - rain
    - snow
    - weather_code
