- platform: speedtest
  minute:
    - 15
  monitored_conditions:
    - upload
    - download
    
- platform: fastdotcom
  minute:
    - 40
  hour:
    - 0
    - 6
    - 12
    - 18
  name: fastdotcom
