- platform: template
  sensors:
    thermo_hvac:
      value_template: '{{ states.climate.thermostat_73_5c_83.state }}'     
      entity_id: climate.thermostat_73_5c_83
    
    living_room_temperature:
      value_template: '{{ states.climate.thermostat_73_5c_83.attributes.current_temperature | float}}'
      unit_of_measurement: '°F'
      entity_id: climate.thermostat_73_5c_83
      
    thermo_fan:
      value_template: '{{ states.climate.thermostat_73_5c_83.attributes.fan }}'
      entity_id: climate.thermostat_73_5c_83
      
    thermo_current_operation:
      value_template: '{{ states.climate.thermostat_73_5c_83.attributes.mode }}'   
      entity_id: climate.thermostat_73_5c_83

    thermo_mode:
      value_template: '{{ states.climate.thermostat_73_5c_83.attributes.mode }}'
      entity_id: climate.thermostat_73_5c_83


