alias: Arriving Home
trigger:
  - platform: state
    entity_id: device_tracker.kevin_gps
    to: 'home'
  - platform: state
    entity_id: device_tracker.allegra_gps
    to: 'home'
condition:
  condition: and
  conditions:
    - condition: time
      after: '15:30:00'
      before: '19:30:00'
action:
  - service: light.turn_on
    entity_id:
      - light.couch_left
      - light.couch_right
      - light.kitchen_table
  - service: input_boolean.turn_off
    entity_id: input_boolean.guest_mode
  - service: python_script.thermostat_engine
