alias: Away From Home at Night
trigger:
  - platform: sun
    event: sunset
    offset: '-00:15:00'
  - platform: state
    entity_id: sensor.occupancy
    to: 'not_home'
condition:
  condition: and
  conditions:
    - condition: time
      after: '16:00:00'
      before: '22:00:00'
    - condition: state
      entity_id: sensor.occupancy
      state: 'not_home'
action:
  - service: light.turn_on
    entity_id:
      - light.couch_left
      - light.couch_right
