# Turn lights off when everyone leaves for work
# group.all_devices is 'not_home' if ALL devices are not home
# Only do this between 7:30am to 10:00am

alias: Away From Home
trigger:
  - platform: state
    entity_id: group.all_devices
    state: 'not_home'
condition:
  - condition: time
    after: '7:30:00'
    before: '10:00:00'
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
action:
  service: light.turn_off
  entity_id: group.all_lights
    