alias: Away From Home
trigger:
  - platform: state
    entity_id: sensor.occupancy
    to: 'not_home'
condition:
  condition: and
  conditions:
    - condition: time
      before: '16:00:00'
    - condition: state
      entity_id: input_boolean.guest_mode
      state: 'off'
action:
    - service: light.turn_off
      entity_id: group.all_lights
    - service: python_script.thermostat_engine 
