# Turn on inside light if it's cloudy midday
alias: Lights Cloudy
trigger:
  - platform: numeric_state
    entity_id: sensor.weather_cloud_coverage
    above: 75
  - platform: numeric_state
    entity_id: sensor.weather_rain
    above: 0.05
condition:
  condition: and
  conditions:
    - condition: time
      after: '10:00:00'
      before: '20:00:00'
    - condition: state
      entity_id: sun.sun
      state: 'above_horizon'
action:
  - service: light.turn_on
    entity_id:
      - light.family_room_couch_left
      - light.family_room_couch_right
      - light.living_room_couch 
