# Turn on inside light if it's cloudy midday
alias: Lights Cloudy
trigger:
  - platform: state
    entity_id: sensor.weather_condition
    to: "lightning"
  - platform: state
    entity_id: sensor.weather_condition
    to: "rainy"
  - platform: state
    entity_id: sensor.weather_condition
    to: "cloudy"
  - platform: state
    entity_id: sensor.weather_condition
    to: "fog"
condition:
  condition: and
  conditions:
    - condition: time
      after: '10:00:00'
      before: '18:00:00'
      weekday:
        - tue
        - thu
        - sat
        - sun
    - condition: state
      entity_id: sun.sun
      state: 'above_horizon'
action:
  - service: light.turn_on
    entity_id:
      - light.family_room_couch_left
      - light.family_room_couch_right
