alias: Daytime Routine
trigger:
    - platform: sun
      event: sunrise
      offset: '+00:30:00'
    - platform: time
      at: '08:00:00'
condition:
    - condition: sun
      after: sunrise
      after_offset: '+00:15:00'

action:
    - service: light.turn_off
      entity_id: light.kitchen_table
    - service: python_script.thermostat_engine
