alias: Evening Routine
trigger:
  - platform: sun
    event: sunset
    offset: '-01:30:00'
action:
  - service: light.turn_on
    entity_id:
      - light.living_room_couch
      - light.family_room_couch_left
      - light.family_room_couch_right
