alias: Evening Routine Home
trigger:
  - platform: sun
    event: sunset
    offset: '00:30:00'
action:
  - service: light.turn_on
    entity_id:
      - light.kitchen_island
      - light.kitchen_table
