alias: Evening Routine
trigger:
  - platform: sun
    event: sunset
    offset: '-00:40:00'
action:
  - service: light.turn_on
    entity_id:
      - light.family_room_couch_left
      - light.family_room_couch_right
      - light.kitchen_island
      - light.kitchen_table
      - light.living_room_couch
