# Turn on holiday lights at sunset
alias: Holiday Lights
trigger:
  - platform: sun
    event: sunset
    offset: '+00:16:00'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: 'input_boolean.christmas_lights'
      state: 'on'
action:
  - service: switch.turn_on
    entity_id: group.outdoor_switches
  - service: switch.turn_off
    entity_id: group.driveway
  - service: light.turn_on
    entity_id: light.porch
    data:
      brightness: 150
      xy_color: [0.1972,0.6781]
