# Turn lights on when someone comes home from work
# group.all_devices is 'home' if ANY device is home
# Do this between 5pm and 7pm

alias: Home From Work
trigger:
  - platform: state
    entity_id: group.all_devices
    state: 'home'
condition:
  condition: and
  conditions:
    - condition: time
      after: '16:00:00'
      before: '19:00:00'
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
    - condition: state
      entity_id: input_boolean.device_tracking_override
      state: 'off'
action:
  service: light.turn_on
  entity_id: group.couch
    