# Turn lights on when someone comes home from work
# group.all_devices is 'home' if ANY device is home
# Do this between 5pm and 7pm

alias: Home From Work
trigger:
  - platform: state
    entity_id: sensor.occupancy
    to: 'home'
condition:
  condition: and
  conditions:
    - condition: time
      after: '16:00:00'
      before: '19:00:00'
      weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
action:
  - service: light.turn_on
    entity_id: group.couch
  - service: light.turn_on
    entity_id: light.kitchen_table
