# Updates input_select based on HVAC status
alias: Thermostat HVAC Update
trigger:
  - platform: state
    entity_id: sensor.thermo_hvac
    state: 'cool'
  - platform: state
    entity_id: sensor.thermo_hvac
    state: 'heat'
  - platform: state
    entity_id: sensor.thermo_hvac
    state: 'auto'
  - platform: state
    entity_id: sensor.thermo_hvac
    state: 'off'
action:
  service: input_select.select_option
  entity_id: input_select.hvac_option
  data_template:
    option: >
      {% if is_state('sensor.thermo_hvac', 'auto') %}
        Auto
      {% elif is_state('sensor.thermo_hvac', 'cool') %}
        Cool
      {% elif is_state('sensor.thermo_hvac', 'heat') %}
        Heat
      {% elif is_state('sensor.thermo_hvac', 'off') %}
        Off
      {% else %}
      {% endif %}