# Sets Away Mode Based on boolean select
alias: Thermostat Away Mode
trigger:
  - platform: state
    entity_id: group.all_devices
    from: 'not_home'
    to: 'home'
  - platform: state
    entity_id: group.all_devices
    from: 'home'
    to: 'not_home'
  - platform: state
    entity_id: input_boolean.hvac_away_mode
    to: 'on'
action:
  service: script.hvac_away_mode