alias: Thermostat Turn On on Weather
trigger:
  platform: state
  entity_id: sensor.weather_temperature
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: input_boolean.thermo_weather
      state: 'on'
    - condition: state
      entity_id: sensor.thermo_hvac
      state: 'off'
action:
  service: script.hvac_set