# Updates input_select based on HVAC status
alias: Thermostat HVAC Update
trigger:
  - platform: state
    entity_id: sensor.thermo_hvac
    to: 'cool'
  - platform: state
    entity_id: sensor.thermo_hvac
    to: 'heat'
  - platform: state
    entity_id: sensor.thermo_hvac
    to: 'auto'
  - platform: state
    entity_id: sensor.thermo_hvac
    to: 'off'
condition:
  - condition: state
    entity_id: input_boolean.hvac_override
    state: 'off'
action:
  service: script.hvac_mode_select