# Sets Away Mode Based on boolean select
alias: Thermostat Away Mode
trigger:
  - platform: state
    entity_id: sensor.occupancy
    from: 'not_home'
    to: 'home'
  - platform: state
    entity_id: sensor.occupancy
    from: 'home'
    to: 'not_home'
  - platform: state
    entity_id: input_boolean.hvac_away_mode
    to: 'on'
  - platform: state
    entity_id: input_boolean.hvac_away_mode
    to: 'off'
action:
  service: script.hvac_away_mode