alias: Thermostat Disable Weather Tracking
trigger:
  - platform: state
    entity_id: input_boolean.thermo_weather
    from: 'on'
    to: 'off'
  - platform: state
    entity_id: input_select.hvac_option
    state: 'Cool'
  - platform: state
    entity_id: input_select.hvac_option
    state: 'Heat'
action:
  service: script.hvac_override_weather