alias: Thermostat Turn On on Weather
trigger:
  - platform: state
    entity_id: sensor.thermo_outside_temp
    from: 'Fair'
  - platform: state
    entity_id: input_boolean.force_hvac_trigger
    from: 'off'
    to: 'on'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: input_boolean.hvac_override
      state: 'off'
    - condition: state
      entity_id: input_boolean.thermo_weather
      state: 'on'
    - condition: state
      entity_id: sensor.thermo_hvac
      state: 'Off'
action:
  service: script.hvac_set