# Sets Away Mode Based on boolean select
alias: Thermostat Away Mode
trigger:
  - platform: state
    entity_id: group.all_devices
    from: 'not_home'
    to: 'home'
  - platform: state
    entity_id: group.all_devices
    from: 'home'
    to: 'not_home'
  - platform: state
    entity_id: input_boolean.hvac_away_mode
    to: 'on'
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: input_boolean.device_tracking_override
      state: 'off'
    - condition: state
      entity_id: input_boolean.hvac_override
      state: 'off'
action:
  service: script.hvac_away_mode