alias: Set Thermostat on Weather
trigger:
  - platform: state
    entity_id: sensor.thermo_outside_temp
    to: 'Fair'
  - platform: state
    entity_id: sensor.thermo_outside_temp
    from: 'Fair'
  - platform: state
    entity_id: input_boolean.force_hvac_trigger
    from: 'off'
    to: 'on'
condition:
  condition: or
  conditions:
    - condition: state
      entity_id: sensor.thermo_hvac
      state: 'Auto'
    - condition: state
      entity_id: sensor.thermo_hvac
      state: 'Off'
action:
  service: script.hvac_set