alias: Thermostat Setting On Weather
trigger:
  platform: state
  entity_id: sensor.weather_temperature
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: input_boolean.thermo_weather
      state: 'on'
    - condition: state
      entity_id: sensor.thermo_hvac
      state: 'auto'
action:
  service: input_select.select_option
  entity_id: input_select.hvac_option
  data_template:
    option: >
      {% if states.sensor.weather_temperature.state | float < states.sensor.thermo_target_high.state | float - 2.0 and states.sensor.weather_temperature.state | float > states.sensor.thermo_target_low.state | float + 2.0 %}
        Off
      {% else %}
        Auto
      {% endif %}