# Turn inside lights off around midnight (before exterior)

alias: Inside Lights at Night
trigger:
  - platform: time
    after: '00:12:03'
    
action:
  service: light.turn_off
  entity_id: group.interior
