# Turn inside lights off around midnight (before exterior)

alias: Lights Inside Off
trigger:
  - platform: time
    at: '00:12:09'
action:
  - service: light.turn_off
    entity_id: light.interior_lights
