# Turn lights on in the morning 
alias: Lights Wakeup
trigger:
  - platform: time
    at: '6:30:37'
action:
  - service: light.turn_on
    entity_id:
      - light.couch_left
      - light.kitchen_table
