# Turn on outside lights off at 12:40 am

alias: Lights Outdoor Off
trigger:
  - platform: time
    at: '00:40:07'
action:
  - service: light.turn_off
    entity_id: light.porch
  - service: switch.turn_off
    entity_id: switch.driveway
