alias: Movie Colors
trigger:
  - platform: state
    entity_id: sensor.media_state
  - platform: state
    entity_id: media_player.shield_android_tv
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: sensor.occupancy
      state: 'home'
    - condition: state
      entity_id: input_boolean.movie_colors
      state: 'on'
action:
  - service: python_script.media_engine

