alias: Nighttime Routine
trigger:
  - platform: time
    at: '21:30:00'
action:
  - service: light.turn_off
    entity_id: light.kitchen_table
  - service: alarm_control_panel.alarm_arm_away
    entity_id: alarm_control_panel.blink_xt_hub
