# Turn on lights if we're not home and it's dark out
alias: Away From Home
trigger:
  - platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 0
condition:
  condition: and
  conditions:
    - condition: time
      after: '18:45:00'
    - condition: state
      entity_id: group.all_devices
      state: 'not_home'
    - condition: state
      entity_id: input_boolean.device_tracking_override
      state: 'off'
action:
  service: scene.turn_on
  entity_id: scene.not_home_at_night
