# Turn on lights if we're not home and it's dark out
alias: Away From Home
trigger:
  - platform: numeric_state
    entity_id: sun.sun
    value_template: '{{ state.attributes.elevation }}'
    below: 0
  - platform: state
    entity_id: group.all_devices
    to: 'not_home'
condition:
  condition: and
  conditions:
    - condition: time
      after: '16:00:00'
      before: '22:00:00'
    - condition: state
      entity_id: group.all_devices
      state: 'not_home'
    - condition: state
      entity_id: input_boolean.device_tracking_override
      state: 'off'
action:
  service: light.turn_on
  entity_id: group.couch
