alias: Notify on SSL Expiry
trigger:
  - platform: numeric_state
    entity_id: sensor.ssl_cert_expiry
    below: 21
action:
  - service: script.notify_engine
    data_template:
      call_ssl_cert_expiry: 1