alias: Notify on Failed Login
trigger:
  - platform: state
    entity_id: sensor.fail2ban_nginxhttpauth
  - platform: state
    entity_id: sensor.fail2ban_hassiptables
  - platform: state
    entity_id: sensor.fail2ban_organizrauth
condition:
  condition: or
  conditions:
    - condition: template
      value_template: '{{ states.sensor.fail2ban_hassiptables.state != "None" }}'
    - condition: template
      value_template: '{{ states.sensor.fail2ban_organizrauth.state != "None" }}'
    - condition: template
      value_template: '{{ states.sensor.fail2ban_nginxhttpauth.state != "None" }}'
action:
  - service: script.notify_kevin_engine
    data:
      call_failed_login: 1