alias: Notify on Failed Login
trigger:
  - platform: state
    entity_id: sensor.fail2ban_nginx_http_auth
  - platform: state
    entity_id: sensor.fail2ban_hass_iptables
  - platform: state
    entity_id: sensor.fail2ban_organizr_auth
condition:
  condition: or
  conditions:
    - condition: template
      value_template: '{{ states.sensor.fail2ban_hass_iptables.state != "None" }}'
    - condition: template
      value_template: '{{ states.sensor.fail2ban_organizr_auth.state != "None" }}'
    - condition: template
      value_template: '{{ states.sensor.fail2ban_nginx_http_auth.state != "None" }}'
action:
  - service: script.notify_kevin_engine
    data:
      call_failed_login: 1
