alias: Notify on Restart
trigger:
  - platform: homeassistant
    event: start
action:
  - service: script.notify_kevin_engine
    data:
      call_on_restart: 1
  - service_template: >
      {% if now().month == 12 %}
        input_boolean.turn_on
      {% else %}
        input_boolean.turn_off
      {% endif %}
    entity_id: input_boolean.christmas_lights
