alias: Notify on SSL Expiry
trigger:
  - platform: numeric_state
    entity_id: sensor.ssl_cert_expiry
    below: 21
action:
  - service: notify.notify_kevin_phone
    data: 
      message: 'Warning - SSL Certificate expires in 21 days and has not been renewed!'