alias: Notify on Washer Status
trigger:
  - platform: state
    entity_id: sensor.washer
    from: 'Not Running'
    to: 'Running'
  - platform: state
    entity_id: sensor.washer
    from: 'Running'
    to: 'Not Running'
action:
  - service: script.notify_all_engine
    data_template:
      call_washer_status: 1