alias: Notify on System Use
trigger:
  - platform: numeric_state
    entity_id: sensor.glances_ram_use
    above: 75.0
    below: 100.0
  - platform: numeric_state
    entity_id: sensor.glances_ram_use_2
    above: 75.0
    below: 100.0
  - platform: numeric_state
    entity_id: sensor.glances_swap_use
    above: 50.0
action:
  - service: script.notify_kevin_engine
    data_template:
      call_system_use: 1