alias: On The Way Home
trigger:
  - platform: state
    entity_id: input_boolean.on_the_way_home
    to: 'on'
action:
  - service: light.turn_on
    entity_id:
      - light.couch_left
      - light.couch_right
      - light.kitchen_table
  - service: python_script.thermostat_engine
  - service: script.notify_all_engine
    data:
      call_on_way_home: 1
