# Turn on outside lights off at 12:40 am

alias: Outdoor Lights Off
trigger:
  - platform: time
    after: '00:40:07'
action:
  - service: light.turn_off
    entity_id: group.exterior
  - service: switch.turn_off
    entity_id: group.outdoor_switches
  - service: switch.turn_off    
    entity_id: group.driveway