#Turn on couch lights if it's raining, someone
# is home, and it's after 11am.
alias: Raining
trigger:
  - platform: state
    entity_id: sensor.pws_weather
    state: 'Rain'
condition:
  condition: and
  conditions:
    - condition: time
      after: '07:00'
      before: '18:00'
    - condition: state
      entity_id: sensor.occupancy
      state: 'home'
action:
  service: light.turn_on
  entity_id: group.couch
