# Turn off lights inside if it's sunny
alias: Lights Sunny
trigger:
  - platform: numeric_state
    entity_id: sensor.weather_cloudiness
    below: 20
condition:
  condition: and
  conditions:
    - condition: time
      after: '12:00:00'
      before: '15:00:00'
    - condition: state
      entity_id: light.living_room_couch
      state: 'on'
action:
  - service: light.turn_off
    entity_id:
      - light.family_room_couch_left
      - light.family_room_couch_right
      - light.living_room_couch
