# Turn on outside lights 15 minutes after sunset

alias: Lights Sunset
trigger:
  - platform: sun
    event: sunset
    offset: '+00:15:00'
action:
  - service: light.turn_on
    entity_id: light.porch
    data:
      brightness: 255
      color_temp: 330
  - service: switch.turn_on
    entity_id: switch.driveway_switch
