alias: 'Heat on Tuesday'
trigger:
  - platform: time
    at: '8:00:00'
condition:
  - condition: time
    weekday:
    - tue
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.guest_mode
