alias: Thermostat Change on Weather
trigger:
  - platform: numeric_state
    entity_id: sensor.dark_sky_temperature
    above: 77
  - platform: numeric_state
    entity_id: sensor.dark_sky_temperature
    below: 55
  - platform: numeric_state
    entity_id: sensor.dark_sky_temperature
    above: 58
    below: 74
  - platform: numeric_state
    entity_id: sensor.living_room_humidity
    above: 58
  - platform: numeric_state
    entity_id: sensor.living_room_humidity
    below: 55
  - platform: template
    value_template: '{{ (states.climate.living_room.attributes.current_temperature | float - states.sensor.dark_sky_temperature.state | float) > 2.0 }}'
  - platform: template
    value_template: '{{ (states.sensor.bedroom_temperature.state | int > 79) and (now().strftime("%H") | int > 21) }}'
  - platform: template
    value_template: '{{ (states.sensor.bedroom_temperature.state | int < 78) and ((now().strftime("%H") | int > 21) or (now().strftime("%H") | int < 5)) }}'

action:
  - service: python_script.thermostat_engine
