alias: 'Heat on Fridays'
trigger:
  - platform: state
    entity_id: sensor.occupancy
    to: 'not_home'
condition:
  - condition: time
    after: '06:00:00'
    before: '10:00:00'
    weekday:
    - fri
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.guest_mode
