# Set thermostat away mode if we're not home
alias: Thermostat Not Home
trigger:
  - platform: state
    entity_id: group.all_devices
    state: 'not_home'
condition:
  - condition: time
    after: '7:30:00'
    before: '10:00:00'
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
action:
  service: thermostat.set_away_mode
  entity_id: thermostat.living_room
  data:
    away_mode: true
