# Turn lights on in the morning 
alias: Wakeup
trigger:
  - platform: time
    at: '6:30:00'
action:
  - service: light.turn_on
    entity_id: light.couch_left
  - service: light.turn_on
    entity_id: light.kitchen_table
