alias: Wakeup Routine
trigger:
  - platform: time
    at: '06:30:30'
action:
  - service: light.turn_on
    entity_id:
      - light.couch_left
      - light.kitchen_table
  - service: alarm_control_panel.alarm_disarm
    entity_id: alarm_control_panel.blink_xt_hub 
