- platform: generic
  still_image_url: !secret radar_link
  name: Home Radar

- platform: local_file
  file_path: /home/hass/images/Temperature.png
  name: Temperature

- platform: local_file
  file_path: /home/hass/images/Internet.png
  name: Internet

- platform: local_file
  file_path: /home/hass/images/Humidity.png
  name: Relative Humidity