- platform: group
  name: Family Room Lights
  entities:
    - light.family_room_couch_right
    - light.family_room_couch_left
    - light.family_room_fireplace

- platform: group
  name: Office Lights
  entities:
    - light.office_desk
    - light.office_corner

- platform: group
  name: Master Bedroom Lights
  entities:
    - light.master_bedroom_door
    - light.master_bedroom_window

- platform: group
  name: Living Room Lights
  entities:
    - light.living_room_couch

- platform: group
  name: Kitchen Lights
  entities:
    - light.kitchen_island_1
    - light.kitchen_island_2

- platform: group
  name: Interior Lights
  entities:
    - light.family_room_lights
    - light.office_lights
    - light.living_room_lights
    - light.kitchen_lights
