name: Home Assistant CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  schedule:
      # Run at 1:05pm UTC every Saturday (8:05am EST)
      - cron: '5 13 * * 6'

jobs:
  hassci:
    name: "Config Check"
    runs-on: ${{ matrix.platform }}
    strategy:
      max-parallel: 2
      matrix:
        platform:
          - ubuntu-latest
        hass-version: ["stable", "beta"]
   
    container:
      image: homeassistant/home-assistant:${{ matrix.hass-version }}
      env:
        TZ: "America/New_York"
      volumes:
        - /tmp:/tmp
        - /tmp:/images
    
    steps:
      - name: Getting config from github
        uses: actions/checkout@v2
      - name: HA Version Check
        run: python -m homeassistant --version
      - name: Copy secrets into configuration folder
        run: |
          cd "$GITHUB_WORKSPACE"
          cp travis_secrets.yaml secrets.yaml
          touch /tmp/test.txt
      - name: Config Check
        run: python -m homeassistant --config $GITHUB_WORKSPACE --script check_config
